#!/bin/bash

# @Author LordOfWizard

MAIN_DIR=$PWD
BUILD_URL=https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

#checking the directories thingy

wget -q 
