#!/bin/bash

# @Author LordOfWizard

MAIN_DIR=$PWD]
echo "This will install the latest spigot version.. if you want custom version change the BUILD_URL in JavaInstallScript/SpigotInstall file"
BUILD_URL=https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

#checking the directories thingy
cd ..
mkdir -p server
cd server/

# downloading the damn BuildTools.jar
wget -q $BUILD_URL -o BuildTools.jar
echo -e "
_________         _________ _______            _________ _        _         
\__   __/|\     /|\__   __/(  ____ \  |\     /|\__   __/( \      ( \        
   ) (   | )   ( |   ) (   | (    \/  | )   ( |   ) (   | (      | (        
   | |   | (___) |   | |   | (_____   | | _ | |   | |   | |      | |        
   | |   |  ___  |   | |   (_____  )  | |( )| |   | |   | |      | |        
   | |   | (   ) |   | |         ) |  | || || |   | |   | |      | |        
   | |   | )   ( |___) (___/\____) |  | () () |___) (___| (____/\| (____/\  
   )_(   |/     \|\_______/\_______)  (_______)\_______/(_______/(_______/  
                                                                            
  _________ _______  _        _______   __________________ _______  _______ 
  \__   __/(  ___  )| \    /\(  ____ \  \__   __/\__   __/(       )(  ____ \
     ) (   | (   ) ||  \  / /| (    \/     ) (      ) (   | () () || (    \/
     | |   | (___) ||  (_/ / | (__         | |      | |   | || || || (__    
     | |   |  ___  ||   _ (  |  __)        | |      | |   | |(_)| ||  __)   
     | |   | (   ) ||  ( \ \ | (           | |      | |   | |   | || (      
     | |   | )   ( ||  /  \ \| (____/\     | |   ___) (___| )   ( || (____/\
     )_(   |/     \||_/    \/(_______/     )_(   \_______/|/     \|(_______/
"
sleep 7
clear
sleep 1
$MAIN_DIR/bin/java_bins/bin/java BuildTools.jar

# changing the name of the file to appropriate name...

JAR=$(ls | grep spigot)
mv $JAR server.jar



