#!/bin/bash
export MAIN_DIR=$PWD
#Installing all the dependencise
sudo apt install -qq screen neofetch wget unzip -y 

echo "export PATH=$PATH:/some/new/path" > ~/.profile
echo "> Dependencies Installtion Completed!"

#Downloading ngrok && Downloading Minecraft Server
mkdir server 

echo ""
echo "-- Pick the following Server type: --"
echo "Type [1] Create Vanilla Server"
echo "Type [2] Create GoMint Server"
echo "Type [3] Create Nukkit Server (Extra Steps needed)"
echo "Type [4] Create PocketmineMP Server"


choiceForServer=1
read choiceForServer

# 0
if [[ -z $choiceForServer ]]; then
	
	echo "> By Default you selected [1]"
    echo "> Installing Vanilla Server..."
    cd BedrockInstallScripts
    chmod +x *
    ./VanillaInstall

# Vanilla
elif [[ $choiceForServer == 1 ]]; then
	
    echo "> Installing Vanilla Server..."
    cd BedrockInstallScripts
    chmod +x *
    ./VanillaInstall

# GoMint
elif [[ $choiceForServer == 2 ]]; then

	echo "> Installing GoMint Server..."
    cd BedrockInstallScripts
    chmod +x *
    ./GoMintInstall

# Nukkit
elif [[ $choiceForServer == 3 ]]; then

	echo "> Installing Nukkit Server..."
    cd BedrockInstallScripts
    chmod +x *
    ./NukkitInstall

# Pocketmine
elif [[ $choiceForServer == 4 ]]; then

	echo "> Installing PocketmineMP Server..."
    cd BedrockInstallScripts
    chmod +x *
    ./PocketmineInstall
# Otherwise
else
    echo "> By Default, you selected [1]"
    echo "> Installing Vanilla Server..."
    cd BedrockInstallScripts
    chmod +x *
    ./VanillaInstall
fi

# Backup install playit.gg in case if first one doesn't download
echo "> Installing Playit.gg..."
cd ..
wget "https://playit.gg/downloads/playit-linux_64-0.4.6" -O playit 
chmod +x playit
echo "> Playit.gg Installation Completed!"
echo ""
echo "-- Do you want to start the server now? --"
echo "Type [1] for Yes"
echo "Type [2] for No"

StartServer=2
read StartServer

if [[ -z $StartServer ]]; then
echo "> By Default, you selected 'No'."
echo "> You can start the server by do ./startserver"

elif [[ $StartServer == 1 ]]; then
./startserver

elif [[ $StartServer == 2 ]]; then
echo "You picked 'No'."
echo "> You can start the server by do ./startserver"

else
echo "> By Default, you selected 'No'."
echo "> You can start the server by do ./startserver"
fi
