#!/bin/bash
export MAIN_DIR=$PWD
echo "> Starting the server up. Please wait..."                                                                                 
echo "> Installing Dependencise..."

sudo apt install -y -qq screen wget  

echo "> Dependencise Installed!"

echo "> Checking Server Type..."
if [ -f $MAIN_DIR/server/bedrock_server ]; then

echo "> Bedrock Server Detected! Starting Server up..."

elif [ ! -f $MAIN_DIR/server/eula.txt ]; then

cd $MAIN_DIR/server
echo "> EULA doesn't exist! Creating one!"
sudo wget https://cdn.discordapp.com/attachments/715123369200189460/846712565530624050/eula.txt
echo "> EULA Completed! Restarting Server"
cd $MAIN_DIR
screen -S server -d -m ./startJavaServer
clear
echo "> Your server just doing a second restart to fix the EULA file."
./startserver
killall screen
elif [ -f $MAIN_DIR/server/eula.txt ]; then
echo "> EULA Detected! Starting Server up..."

else
echo "> Your server isn't setup properly. Force uninstall..."
cd $MAIN_DIR
./uninstall
echo "> Comfirmed Uninstallation! Restarting Installation..."
./install
fi


screen -S server -d -m ./startJavaServer # Starting Java Server
screen -S server -d -m ./startBedrockServer # Starting Bedrock Server
screen -S afk -d -m ./startAfk #Starting AFK app aka bpytop.
screen -S playit -d -m ./startPlayIt # Starting Playit

cd $MAIN_DIR/server
screen -S server -d -m ./bin/php7/bin/php ./PocketMine-MP.phar --no-wizard --disable-ansi # Starting PocketmineMP
screen -S server -d -m java --add-opens java.base/java.nio=io.netty.common --add-exports java.base/jdk.internal.misc=io.netty.common -p modules -m gomint.server/io.gomint.server.Bootstrap # Starting GoMint
cd $MAIN_DIR

echo "-- Your Server is now ONLINE! --"
echo
echo "Type [screen -ls] to check the Running Processes"
echo "Type [screen -r server] to enter the Server Console"
echo "Type [screen -r playit] to view your Server IP"
echo ""
echo "> To stop your server, type './stopserver' to stop"
