#!/bin/bash
export MAIN_DIR=$PWD
export JAVA=$MAIN_DIR/bin/java_bins/bin/java
cd server

grep MemTotal /proc/meminfo # some new stuff 

#uncomment this below line only if the server you are running is 1.17+ (if it is uncommented by default keep it as it is).
$JAVA -Xmx16G -Xms16G -jar server.jar nogui
# for 1.16 or lower uncomment this line
#java -Xmx16G -Xms16G -jar server.jar nogui
