#!/bin/bash
export MAIN_DIR=$PWD
echo "> Checking..."

# Begin Uninstalling Server
if [ ! -d $MAIN_DIR/server ]; then

echo "> You haven't installed the server yet..."


elif [ -d $MAIN_DIR/server ]; then
echo "> Server Folder Detected!"
echo " -- Are you sure you want to uninstall and delete your server? --"
echo "Type [1] for Yes"
echo "Type [2] for No"

UninstallPick=1
read UninstallPick

if [[ -z $UninstallPick ]]; then
	
echo "> By Default, you selected 'No'"
echo "> Abort!"

elif [[ $UninstallPick == 1 ]]; then
sudo rm -r server
sudo rm -rf bin
killall screen
echo "> Uninstall Complete! To make a new server, do ./install"

elif [[ $UninstallPick == 2 ]]; then
echo "> Abort!"

else
echo "> Abort!"
fi
fi
