#!/bin/bash

echo ''
echo '######################################################'
echo '#####   THIS JUST UPDATES THE MCSERVER PROJECT   #####'
echo '#####           NOT YOUR MINECRAFT SERVER        #####'
echo '######################################################'
echo ''

mkdir -p $PWD/../update_files

git clone https://github.com/lordofwizard/mcserver $PWD/../update_files/
rm ../update_files/startserver ../update_files/startJavaServer ../update_files/startBedrockServer

# some java/bedrock installs overwrite the startup scripts
if [ -d 'server' ]; then
	mv ./server/ ../update_files
	mv ./startserver ../update_files
	mv ./startJavaServer ../update_files
	mv ./startBedrockServer ../update_files
	mv ./bin/ ../update_files/
fi
rm -rf *
mv ../update_files/* .
rm -rf ../update_files

echo -e '\n done \n'
