#!/bin/bash

echo
echo '######################################################'
echo '#####   THIS JUST UPDATES THE MCSERVER PROJECT   #####'
echo '#####           NOT YOUR MINECRAFT SERVER        #####'
echo '######################################################'
echo

MAIN_DIR=$PWD
mkdir -p $MAIN_DIR/../update_files

git clone https://github.com/lordofwizard/mcserver $MAIN_DIR/../update_files/
rm ../update_files/startserver ../update_files/startJavaServer ../update_files/startBedrockServer
if [ -d 'server' ]; then
	mv server/ ../update_files
	mv startserver ../update_files
	mv startJavaServer ../update_files
	mv startBedrockServer ../update_files
fi
mv update ../update_files
rm -rf *
mv ../update_files/* .
rm -rf ../update_files
